Update readme and client app
ITLabRTUMIREA/RZHD pull request #13
Opened 2021-03-31 14:08 UTC by Suput

2021-03-31 14:10 UTC, Suput commented
Close #11

2021-04-01 10:43 UTC, CAPCHIK requested changes

2021-04-01 10:43 UTC, CAPCHIK commented on README.md
> +## Проект с хакатона Цифровой прорыв
Стоит дописать год хакатона

2021-04-01 14:16 UTC, CAPCHIK approved these changes

2021-04-01 14:16 UTC, CAPCHIK commented
@Suput Он и должен быть WIP?

2021-04-01 14:31 UTC, merged